### ISSUE TITLE
CAPI As my API Gateway

### ISSUE THREAD

**Issue by JustJavaConsultancy** [surisoft-io/capi#62]
Want to try Apache Camel as my API Gateway

**Comment by rodrigoserracoelho** [comment]
Hello, thanks for your message, did you try already to install CAPI?

**Comment by JustJavaConsultancy** [comment]
Yes please, I have set it up and run it as Springboot application. Unfortunately, when I wanted to access it on localhost:8183, I'm getting an error. This is what I'm currently looking at now.

Thanks 

⁣Get BlueMail for Android ​

**Comment by rodrigoserracoelho** [comment]
Hello, CAPI HTTP (Rest) endpoint is 8380.
So, if you clone the repo and run it, you will be able to access it on:

- Routing traffic 8380
- Metrics 8381
- Websockets 8382.

Keep in mind you need a running Consul instance do register your services.
If you provide me an email we can organize a quick demo, free of charge of course.

BR,
Rodrigo

**Comment by JustJavaConsultancy** [comment]
Thanks so much @rodrigoserracoelho my email is kazeem.akinrinde72@gmail.com
